function(streamstat_set_warnings target_name)
    if (MSVC)
        target_compile_options(${target_name} PRIVATE /W4)
        if (STREAMSTAT_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE /WX)
        else()
            target_compile_options(${target_name} PRIVATE /WX-)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
        if (STREAMSTAT_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
endfunction()
